In [2]:
import numpy as np

In [76]:
list_ = [ '1' , '2' , '3', '4' , '5']
array_list = np.array(object = list_)

In [77]:
array_list

array(['1', '2', '3', '4', '5'], dtype='<U1')

### Q1. Is there any difference in the data type of variables list_ and array_list? If there is then write a code to print the data types of both the variables.

In [78]:
type(list_)

list

In [ ]:
type(array_list)

### Q2. Write a code to print the data type of each and every element of both the variables list_ and arra_list.

In [56]:
for i in list_:
    print (type(i))

<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>


In [63]:
for i in array_list:
    print (type(i))

<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>


### Q3. Considering the following changes in the variable, array_list:

### Will there be any difference in the data type of the elements present in both the variables, list_ and arra_list? If so then print the data types of each and every element present in both the variables, list_ and arra_list.

In [69]:
import numpy as np
list_ = ['1' , '2' , '3' , '4' , '5' ]
array_list = np.array(object = list_, dtype = int)

In [70]:
for i in list_:
    print (type(i))

<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>


In [71]:
for j in array_list:
    print (type(j))

<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>


### Consider the below code to answer further questions:

### Q4. Write a code to find the following characteristics of variable, num_array:
### (i) shape
### (ii) size

In [20]:
import numpy as np

In [21]:
num_list = [ [ 1 , 2 , 3 ] , [ 4 , 5 , 6 ] ]
num_array = np.array(object = num_list)

In [22]:
num_array.shape

(2, 3)

In [23]:
num_array.size

6

### Q5. Write a code to create numpy array of 3*3 matrix containing zeros only, using a numpy array creation function.

In [33]:
matrix = np.zeros((3,3))

In [34]:
matrix

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [35]:
matrix.size

9

### Q6. Create an identity matrix of shape (5,5) using numpy functions?
### [Hint: An identity matrix is a matrix containing 1 diagonally and other elements will be 0.]

In [42]:
indentity = np.eye(5)

In [43]:
indentity

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [75]:
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])